### ISSUE TITLE
Sign with Google popup opens and closes

### ISSUE THREAD

**Issue by paradoxalan** [Janamou/firebase-demo#3]
Hello

I'm new to Dart, and ran the app with the command 'pub server' and when i try to sign in with google, the popup login opens and closes without any error message. I have activated login with Google on the Firebase console as documented. Am i forgetting something?

Thanks

**Comment by Janamou** [comment]
Hi @paradoxalan,

thanks for the message. Aren't you logged then? This happens to me when I
have already authorized myself to sign in with Google there once. Auth's
currentUser object is not null then. Do you have it same?

Thanks


On May 16, 2017 10:14 AM, "Alan Rodrigues" <notifications@github.com> wrote:

Hello

I'm new to Dart, and ran the app with the command 'pub server' and when i
try to sign in with google, the popup login opens and closes without any
error message. I have activated login with Google on the Firebase console
as documented. Am i forgetting something?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Janamou/firebase-demo/issues/3>, or mute the thread

**Comment by paradoxalan** [comment]
Might be. Not sure, probably. But after that the UI should update the navbar on top with my name or something?

**Comment by paradoxalan** [comment]
The error was caused by databaseUrl with wrong value.
I was getting this error in js console:
Refused to display in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'

Now it works, thanks!
